### ISSUE TITLE
No ROS environment sourced. 

### ISSUE THREAD

**Issue by lpacademy0712** [RobotecAI/ros2-for-unity#32] opened 2022-01-26 16:01 UTC
I have strictly followed the instructions in readme, and there are no errors reported during the period. However, "no ROS environment sourced." appeared during the initial test Problems. I'm sure I've run "source / opt / ROS / foxy / setup. bash" in the command window. Who can tell me how to operate to avoid such mistakes? I'm a novice, please give me a detailed operation description, thank you!

**Comment by lpacademy0712** [comment] 2022-01-26 16:02
![2022-01-26 23-43-29屏幕截图](https://user-images.githubusercontent.com/79342727/151199637-3707914d-ef98-4ec2-a69e-7e38aa33405a.png)
![2022-01-26 23-44-08屏幕截图](https://user-images.githubusercontent.com/79342727/151199645-e8977c71-7669-4442-a82f-49d4401fcf29.png)

**Comment by lpacademy0712** [comment] 2022-01-26 16:13
![Uploading 2022-01-27 00-09-13屏幕截图.png…]()

**Comment by lpacademy0712** [comment] 2022-01-26 16:13
![Uploading 2022-01-27 00-09-13屏幕截图.png…]()

**Comment by pijaro** [comment] 2022-01-28 08:14
Hello, thank you for using `ros2-for-unity`!

Did you include `source /opt/ROS/foxy/setup.bash` line in `~/.profile` file? If yes - did you restart ubuntu?

If you did not use `profile` file, then how did you launch the editor? If you run `source /opt/ROS/foxy/setup.bash` in a console then you have to run the editor within the same console or it won't use the sourced variables. To launch editor in console window:

`<PATH_TO_UNITY_EDITOR> -projectPath <PATH_TO_PROJECT>`

Unity Editor is most commonly installed in `~/Unity/Hub/Editor/<VERSION>/Editor/Unity`.

**Comment by adamdbrw** [comment] 2022-02-01 11:34
Also please make sure to restart UnityHub since it holds env variables which were set at the time it was started.

**Comment by adamdbrw** [comment] 2022-02-09 13:16
@lpacademy0712 did any of our advice help?

**Comment by pijaro** [comment] 2022-03-17 07:50
@giorgiozannini I'm looking into it :+1:

**Comment by giorgiozannini** [comment] 2022-03-17 08:09
Thanks a lot!!!

**Comment by pijaro** [comment] 2022-03-17 08:37
@giorgiozannini Current example scripts require `ROS2UnityComponent` to be in the same game object. We can see that this is definitely not optimal, we will change it in a near future.

And indeed, this isn't obvious with the current version of the readme. We will address it. Meanwhile please try to move `ROS2UnityComponent` to a game object with examples script (or move them all to one script).

**Comment by giorgiozannini** [comment] 2022-03-17 08:58
It works! thanks a lot for your help, I wish you a wonderful rest of the day!
Giorgio

**Comment by pijaro** [comment] 2022-03-18 14:35
Glad I could help :smiley: 

Closing since the issue is resolved.

**Closed as completed by pijaro** 2022-03-18 14:35 UTC
