### ISSUE TITLE
CMake Error - Target Names - Windows 10 - Humble

### ISSUE THREAD

**Issue by Mgenenger** [RobotecAI/ros2-for-unity#63] opened 2023-02-27 11:52 UTC
When running the ./build-ps1 command, I get the following error:

![image](https://user-images.githubusercontent.com/106382909/221556870-64745c0e-6bda-4d65-8a1a-9e95da00eb3f.png)

This happens on package 16/47. I tried it with CMake version 3.24.0 and 3.25.0. For this I have the Ament_cmake version 1.3.2 and Windows SDK version 10.0.19041.0 on Windows 10.
Do you have a quick idea or a workaround? Is the whole thing possibly a Windows problem and on Ubuntu the error does not exist? Thanks for your help.

**Comment by adamdbrw** [comment] 2023-03-17 16:16
We were not able to reproduce the bug when using Windows 10.
This could very likely be platform-specific, it is hard to tell.
Do you still have the problem?

**Comment by pijaro** [comment] 2023-03-19 21:12
To double-check, have you followed the important notices for Windows? 
https://github.com/RobotecAI/ros2cs/blob/master/README-WINDOWS.md#important-notices

From my experience, most of the Windows issues are related to insufficient permissions (run PowerShell with admin rights) or path lengths (change the limit in the Windows registry).

**Comment by Mgenenger** [comment] 2023-03-20 07:28
Hey, thank you very much for the feedback. I found a way around the error with ROS noetic and Ros#. There were no difficulties. 
I ran PowerShell as admin as well as enabled path length. 
For my project ROS is sufficient and I don't necessarily need to work with ROS2, therefore you can neglect the problem for now. I hope that this error is really only with me.

**Comment by pijaro** [comment] 2023-03-20 07:47
:+1: I think that we can close it then.

**Closed by pijaro** 2023-03-20 07:47 UTC
Labels: bug
